#!/bin/zsh

#
# Create a list of items that are known (recently seen) to have
# arbitrage opportunities. When accessing the auction house this
# list can be scanned to see what arbitrages are available at
# that moment.
#

LATEST=~/dev/wow/generated/arbitrageLatest.log

echo "local ItemIDs = {"
# Collect item arbitrages of the most recent scan
sort -un ${LATEST}
echo "}"
echo
echo "ArbitrageCache = {"
echo "    ItemIDs = ItemIDs,"
echo "}"
